#!/bin/bash

#compile keygen
gcc -o keygen keygen.c

#compile otp_enc
gcc -o otp_enc otp_enc.c

#compile otp_dec
gcc -o otp_dec otp_dec.c

#compile otp_enc_d
gcc -lpthread -o otp_enc_d otp_enc_d.c queue.c

#compile otp_dec_d
gcc -lpthread -o otp_dec_d otp_dec_d.c queue.c

